### ISSUE TITLE
last newline suppression

### ISSUE THREAD

**Issue by paolino** [unclechu/haskell-qm-interpolated-string#6]
Hi, thanks for this package.
It looks like 
```
[qmb|
a
b
|]
```
is not producing "a\nb\n"  but "a\nb"

**Comment by unclechu** [comment]
@paolino Hello. It's supposed to work this way, enough tests were written [here](https://github.com/unclechu/haskell-qm-interpolated-string/blob/master/test/QMB/Spec.hs) to check it works exactly like that.

If you want it, you could explicitly write it:
```haskell
[qmb|
a
b\n
|]
```

**Comment by unclechu** [comment]
I'm keeping it open, I'll add mentioning of this to docs to reduce confusion about this in the future.
